import "dotenv/config";
import express from "express";
import { createServer as createViteServer } from "vite";
import multer from "multer";
import Database from "better-sqlite3";
import { GoogleGenAI } from "@google/genai";

// Initialize Database
const db = new Database("leads.db");
db.exec(`
  CREATE TABLE IF NOT EXISTS leads (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT,
    email TEXT,
    phone TEXT,
    style TEXT,
    timestamp DATETIME DEFAULT CURRENT_TIMESTAMP
  )
`);

// Initialize Gemini AI
// Note: The API key is injected via process.env.GEMINI_API_KEY or process.env.API_KEY
const apiKey = process.env.GEMINI_API_KEY || process.env.API_KEY;

if (!apiKey) {
  console.warn("Warning: GEMINI_API_KEY or API_KEY not found in environment variables.");
}

const ai = new GoogleGenAI({ apiKey: apiKey });

async function startServer() {
  const app = express();
  const PORT = parseInt(process.env.PORT || "3001", 10);

  // Middleware for parsing JSON and form data
  app.use(express.json());
  app.use(express.urlencoded({ extended: true }));

  // Multer setup for file uploads (in memory)
  const upload = multer({ storage: multer.memoryStorage() });

  // API Routes
  app.post("/api/stage-room", upload.single("image"), async (req, res) => {
    try {
      const { name, email, phone, style } = req.body;
      const file = req.file;

      if (!file) {
        return res.status(400).json({ error: "No image uploaded" });
      }

      // 1. Save Lead
      const stmt = db.prepare(
        "INSERT INTO leads (name, email, phone, style) VALUES (?, ?, ?, ?)"
      );
      stmt.run(name, email, phone, style);

      // 2. Call Gemini API for Virtual Staging
      // Convert buffer to base64
      const base64Image = file.buffer.toString("base64");
      const mimeType = file.mimetype;

      const prompt = `
        Act as a professional interior designer.
        The user has provided a photo of an empty room.
        They want to see it virtually staged in the following style: "${style}".
        
        Please generate a photorealistic image of the room fully furnished in that style.
        Also, provide a short, enthusiastic paragraph explaining your design choices and why this style works for the space.
      `;

      const response = await ai.models.generateContent({
        model: "gemini-2.5-flash-image",
        contents: {
          parts: [
            {
              text: prompt,
            },
            {
              inlineData: {
                mimeType: mimeType,
                data: base64Image,
              },
            },
          ],
        },
      });

      let generatedImageBase64 = null;
      let designStory = "";

      // Parse response for image and text
      if (response.candidates && response.candidates[0].content.parts) {
        for (const part of response.candidates[0].content.parts) {
          if (part.inlineData) {
            generatedImageBase64 = part.inlineData.data;
          } else if (part.text) {
            designStory += part.text;
          }
        }
      }

      if (!generatedImageBase64) {
        // Fallback or error handling if no image is returned
        // Sometimes the model might refuse or fail to generate an image
        console.error("No image generated by Gemini");
        return res.status(500).json({ 
          error: "Failed to generate staged image. The model might have refused the request or encountered an error." 
        });
      }

      res.json({
        image: `data:image/png;base64,${generatedImageBase64}`,
        story: designStory.trim(),
      });

    } catch (error: any) {
      console.error("Error in /api/stage-room:", error);
      res.status(500).json({ error: error.message || "Internal Server Error" });
    }
  });

  app.get("/api/leads", (req, res) => {
    const leads = db.prepare("SELECT * FROM leads ORDER BY timestamp DESC").all();
    res.json(leads);
  });

  // Vite middleware for development
  if (process.env.NODE_ENV !== "production") {
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: "spa",
    });
    app.use(vite.middlewares);
  } else {
    // In production, serve static files from dist
    // (This part is for completeness, though in this env we mostly run dev)
    app.use(express.static("dist"));
  }

  app.listen(PORT, "0.0.0.0", () => {
    console.log(`Server running on http://localhost:${PORT}`);
  });
}

startServer();
